services:
  nimbusguard-base:
    build:
      context: docker
      dockerfile: base.Dockerfile
    image: nimbusguard-base:latest
    command: ["echo", "Base image built successfully"]

  consumer:
    build:
      context: src/consumer
      dockerfile: Dockerfile
    image: nimbusguard-consumer:latest
    container_name: nimbusguard-consumer
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    depends_on:
      - nimbusguard-base
    volumes:
      - ./src/consumer:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  default:
    name: nimbusguard-network 