global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nimbusguard-consumer-workload'
    static_configs:
      - targets: ['consumer-workload:8080']
    metrics_path: /metrics
    scrape_interval: 10s
    
  - job_name: 'nimbusguard-load-generator'
    static_configs:
      - targets: ['load-generator:8081']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'nimbusguard-operator'
    static_configs:
      - targets: ['nimbusguard-operator:8000']  # Prometheus metrics port
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'nimbusguard-operator-api'
    static_configs:
      - targets: ['nimbusguard-operator:8090']  # FastAPI metrics endpoint
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 